name: Build and Deploy Standalone Next.js to CloudPanel

on:
  push:
    branches:
      - main # Ganti dengan branch utama Anda jika berbeda (misal: master)

jobs:
  build-and-deploy:
    name: Build & Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Next.js Site
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Tambahkan environment variables lain di sini jika dibutuhkan saat build

      - name: Prepare Standalone Assets
        run: |
          cp -r public .next/standalone/public
          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/static

      - name: SFTP Standalone Code to CloudPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: ".next/standalone/**"
          target: "/home/mantap-jakarta/htdocs/jakartalanyard.com"
          strip_components: 2
